### ISSUE TITLE
Documentation nonexistent/unclear - 3 parsers - which are included or prequisites for the others?

### ISSUE THREAD

**Issue by johnmccash** [timetology/nw#2]
I'm not sure exactly what the differences are between ssl_ja3, and sslfingerprint. Does sslfingerprint require ssl_ja3 as a prerequisite, and build upon it? Or does it deprecate it?

Likewise, I'm unclear on the exact distinction between ir_sslclientident and ir_sslfingerprint. Does ir_sslfingerprint include all the functionality of ir_sslclientident, or is one of these a complimentary add-on for the other?

If I dig through the code a bit, it LOOKS like sslfingerprint is intended to deprecate ssl_ja3, but if that's the case, why was ssl_ja3 updated more recently?

It also LOOKS like ir_sslclientident doesn't actually calculate the ja3 hash, and must just be adding additional table data for client identification... Is that correct?

Thanks

**Comment by timetology** [comment]
Use the parser in https://github.com/timetology/nw/tree/master/parsers/ssl_ja3 The options file is used for ja3 -> Known Client mapping.
